language: php

matrix:
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'

install:
  - composer install --prefer-dist

before_script:
  - phpenv rehash

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
