name: Tests

on: [ 'push', 'pull_request' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        php: [ '8.0', '8.1' ]
        dependency-version: [ prefer-lowest, prefer-stable ]
    env:
      OS: ${{ matrix.os }}
      PHP: ${{ matrix.php }}
      DEPENDENCY_VERSION: ${{ matrix.dependency-version }}

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom
          tools: composer:v2
          coverage: pcov

      - name: Install PHP dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress

      - name: Unit Tests
        run: ./vendor/bin/pest --colors=always --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,PHP,DEPENDENCY_VERSION
